volumes:
  cache:
    driver: local
  database:
    driver: local

services:
  mongo-tenmans:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27100:27017"
    volumes:
      - database:/data/db

  tenmans:
    container_name: tenmans
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27101:3000"
    env_file:
      - .env
    volumes:
      - cache:/var/lib/cache
    depends_on:
      - mongo-tenmans

networks:
  default:
    driver: bridge