name: Daily Restart

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  restart:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Restart Containers
        run: docker compose restart
